name: officesyndromehelper
description: "Office Syndrome Helper - แอปช่วยเตือนออกกำลังกายสำหรับคนทำงาน"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # State Management & Navigation
  get: ^4.6.6
  
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Notifications & Background Tasks
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  android_alarm_manager_plus: ^4.0.3
  
  # Permissions
  permission_handler: ^11.3.1
  
  # UI Components
  percent_indicator: ^4.2.1
  
  # Utilities
  uuid: ^4.4.0
  intl: ^0.19.0
  
  # Security
  flutter_secure_storage: ^9.2.2
  
  # Fonts & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  
  # Testing & Linting
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/data/
    - assets/images/
  
  # Fonts
  fonts:
    - family: NotoSansThai
      fonts:
        - asset: assets/fonts/NotoSansThai-Regular.ttf
        - asset: assets/fonts/NotoSansThai-Bold.ttf
          weight: 700